name: Analyze with CodeGuru Reviewer

on: [push]

permissions:
  id-token: write
  contents: read
  security-events: write 

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
    - name: Assume IAM role
      id: assume-iam-role
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2
    
    - name: Check out repository
      uses: actions/checkout@v2
      if: steps.assume-iam-role.outcome == 'success'
      with:
        fetch-depth: 0
        
    - name: Set up JDK
      if: steps.assume-iam-role.outcome == 'success'
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build project with Gradle
      if: steps.assume-iam-role.outcome == 'success'
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: CodeGuru Reviewer
      id: analysis
      uses: aws-actions/codeguru-reviewer@v1.1
      if: steps.assume-iam-role.outcome == 'success'
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-github-profiler-demo-048169001733-uw2
        build_path: ./build/classes

    - name: Upload analysis results as workflow artifact
      if: steps.assume-iam-role.outcome == 'success' && steps.analysis.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: codeguru-results-sarif-json
        path: ./codeguru-results.sarif.json

    - name: Summarize analysis results
      if: steps.assume-iam-role.outcome == 'success' && steps.analysis.outcome == 'success'
      run: |
        jq '.runs[0].results[] | {ruleId: .ruleId, firstUri: .locations[0].physicalLocation.artifactLocation.uri, firstLine: .locations[0].physicalLocation.region.startLine} | join(" ")' ./codeguru-results.sarif.json > codeguru-results-summary.txt

    - name: Upload summary of analysis results as workflow artifact
      if: steps.assume-iam-role.outcome == 'success' && steps.analysis.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: codeguru-results-summary-txt
        path: ./codeguru-results-summary.txt

    - uses: jwalton/gh-find-current-pr@v1
      id: find-current-pr

    - name: Add comment to PR with summary of analysis results
      if: steps.assume-iam-role.outcome == 'success' && steps.analysis.outcome == 'success'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.find-current-pr.outputs.pr }}
        path: ./codeguru-results-summary.txt

    ###### This won't work until repo is public
    #
    # - name: Upload analysis results to be shown on the GitHub Security Scans UX
    #   if: steps.assume-iam-role.outcome == 'success' && steps.analysis.outcome == 'success'
    #   uses: github/codeql-action/upload-sarif@v1
    #   with:
    #     sarif_file: codeguru-results.sarif.json
